"""
HTML report generator for audit reports.
"""
from typing import Dict, List, Any, Optional
import os
from datetime import datetime
from pathlib import Path
import json
from jinja2 import Environment, FileSystemLoader, select_autoescape

from shared.utils.logging import logger
from services.reporting_service.config import config


class HTMLGenerator:
    """Generates HTML audit reports with interactive features."""
    
    def __init__(self):
        # Setup Jinja2 environment
        templates_path = Path(config.templates_dir)
        self.env = Environment(
            loader=FileSystemLoader(templates_path),
            autoescape=select_autoescape(['html', 'xml']),
            trim_blocks=True,
            lstrip_blocks=True
        )
        
        # Custom filters
        self.env.filters['json'] = lambda obj: json.dumps(obj, indent=2, default=str)
        self.env.filters['severity_color'] = self._get_severity_color
        self.env.filters['priority_color'] = self._get_priority_color
        
        # Ensure default templates exist
        self._ensure_default_templates()
    
    def _ensure_default_templates(self):
        """Ensure default HTML templates exist."""
        templates_dir = Path(config.templates_dir)
        templates_dir.mkdir(parents=True, exist_ok=True)
        
        # Create base template if it doesn't exist
        base_template = templates_dir / "base_template.html"
        if not base_template.exists():
            self._create_default_base_template()
        
        # Create audit report template if it doesn't exist
        audit_template = templates_dir / "audit_report.html"
        if not audit_template.exists():
            self._create_default_audit_template()
        
        # Create CSS file if it doesn't exist
        css_file = templates_dir / "style.css"
        if not css_file.exists():
            self._create_default_css()
    
    def _create_default_base_template(self):
        """Create default base template."""
        template_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Aquila Audit Report{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        {{ self.css()|safe }}
    </style>
    {% block extra_css %}{% endblock %}
</head>
<body>
    <div class="container">
        {% block header %}
        <header class="report-header">
            <div class="company-info">
                <h1>{{ company_name }}</h1>
                <p>{{ company_address }}</p>
                <p><a href="{{ company_website }}">{{ company_website }}</a></p>
            </div>
            {% if company_logo_exists %}
            <div class="company-logo">
                <img src="{{ company_logo_path }}" alt="{{ company_name }} Logo">
            </div>
            {% endif %}
        </header>
        {% endblock %}
        
        <main>
            {% block content %}{% endblock %}
        </main>
        
        {% block footer %}
        <footer class="report-footer">
            <div class="footer-content">
                <p>Generated on {{ generated_date }} by {{ generated_by }}</p>
                {% if confidential %}
                <p class="confidential-notice">
                    <i class="fas fa-lock"></i> CONFIDENTIAL - For authorized personnel only
                </p>
                {% endif %}
                <p class="footer-disclaimer">
                    This report was generated by Aquila Audit. All rights reserved.
                </p>
            </div>
        </footer>
        {% endblock %}
    </div>
    
    {% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
    <script>
        {{ self.js()|safe }}
    </script>
    {% endblock %}
    
    {% block extra_scripts %}{% endblock %}
</body>
</html>
"""
        
        template_path = Path(config.templates_dir) / "base_template.html"
        with open(template_path, 'w') as f:
            f.write(template_content)
    
    def _create_default_audit_template(self):
        """Create default audit report template."""
        template_content = """{% extends "base_template.html" %}

{% block title %}{{ report.title }} - {{ company_name }}{% endblock %}

{% block content %}
<div class="audit-report">
    <!-- Cover Page -->
    <section class="cover-page">
        <div class="cover-content">
            <h1 class="report-title">{{ report.title }}</h1>
            {% if report.subtitle %}
            <h2 class="report-subtitle">{{ report.subtitle }}</h2>
            {% endif %}
            
            <div class="report-metadata">
                <table class="metadata-table">
                    <tr>
                        <th>Report ID:</th>
                        <td>{{ report.report_id }}</td>
                    </tr>
                    <tr>
                        <th>Generated:</th>
                        <td>{{ report.generated_date }}</td>
                    </tr>
                    <tr>
                        <th>Period:</th>
                        <td>{{ report.period }}</td>
                    </tr>
                    <tr>
                        <th>Scope:</th>
                        <td>{{ report.scope }}</td>
                    </tr>
                    <tr>
                        <th>Generated By:</th>
                        <td>{{ report.generated_by }}</td>
                    </tr>
                    {% if report.tenant %}
                    <tr>
                        <th>Tenant:</th>
                        <td>{{ report.tenant.name }}</td>
                    </tr>
                    {% endif %}
                </table>
            </div>
            
            {% if report.confidential %}
            <div class="confidential-banner">
                <i class="fas fa-shield-alt"></i>
                <span>CONFIDENTIAL - RESTRICTED ACCESS</span>
            </div>
            {% endif %}
        </div>
    </section>
    
    <!-- Table of Contents -->
    <section class="toc-section">
        <h2><i class="fas fa-list"></i> Table of Contents</h2>
        <nav class="toc-nav">
            <ul>
                <li><a href="#executive-summary">Executive Summary</a></li>
                <li><a href="#findings-summary">Findings Summary</a></li>
                <li><a href="#detailed-findings">Detailed Findings</a></li>
                {% if report.recommendations %}
                <li><a href="#recommendations">Recommendations</a></li>
                {% endif %}
                {% if report.appendix %}
                <li><a href="#appendix">Appendix</a></li>
                {% endif %}
            </ul>
        </nav>
    </section>
    
    <!-- Executive Summary -->
    <section id="executive-summary" class="executive-summary">
        <h2><i class="fas fa-chart-line"></i> Executive Summary</h2>
        
        {% if report.executive_summary %}
        <div class="summary-text">
            {{ report.executive_summary }}
        </div>
        {% endif %}
        
        {% if report.metrics %}
        <div class="key-metrics">
            <h3>Key Metrics</h3>
            <div class="metrics-grid">
                <div class="metric-card total">
                    <div class="metric-label">Total Findings</div>
                    <div class="metric-value">{{ report.metrics.total_findings }}</div>
                </div>
                <div class="metric-card critical">
                    <div class="metric-label">Critical</div>
                    <div class="metric-value">{{ report.metrics.critical }}</div>
                </div>
                <div class="metric-card high">
                    <div class="metric-label">High</div>
                    <div class="metric-value">{{ report.metrics.high }}</div>
                </div>
                <div class="metric-card medium">
                    <div class="metric-label">Medium</div>
                    <div class="metric-value">{{ report.metrics.medium }}</div>
                </div>
                <div class="metric-card low">
                    <div class="metric-label">Low</div>
                    <div class="metric-value">{{ report.metrics.low }}</div>
                </div>
                {% if report.metrics.risk_score %}
                <div class="metric-card risk-score">
                    <div class="metric-label">Risk Score</div>
                    <div class="metric-value">{{ report.metrics.risk_score }}/10</div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endif %}
        
        {% if report.top_findings %}
        <div class="top-findings">
            <h3>Top Findings</h3>
            <div class="findings-list">
                {% for finding in report.top_findings[:5] %}
                <div class="finding-card {{ finding.severity|lower }}">
                    <div class="finding-header">
                        <span class="finding-number">{{ loop.index }}.</span>
                        <h4>{{ finding.title }}</h4>
                        <span class="severity-badge {{ finding.severity|lower }}">{{ finding.severity }}</span>
                    </div>
                    <p class="finding-description">{{ finding.description }}</p>
                    <div class="finding-meta">
                        <span><i class="fas fa-cogs"></i> {{ finding.rule_name }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </section>
    
    <!-- Findings Summary -->
    <section id="findings-summary" class="findings-summary">
        <h2><i class="fas fa-search"></i> Findings Summary</h2>
        
        {% if report.metrics %}
        <div class="charts-container">
            <div class="chart-card">
                <h3>Findings by Severity</h3>
                <canvas id="severityChart"></canvas>
            </div>
            <div class="chart-card">
                <h3>Findings Over Time</h3>
                <canvas id="timelineChart"></canvas>
            </div>
        </div>
        
        <div class="severity-breakdown">
            <h3>Detailed Breakdown</h3>
            <div class="breakdown-grid">
                {% for severity, count in {
                    'critical': report.metrics.critical,
                    'high': report.metrics.high,
                    'medium': report.metrics.medium,
                    'low': report.metrics.low
                }.items() if count > 0 %}
                <div class="breakdown-item {{ severity }}">
                    <div class="breakdown-label">{{ severity|title }}</div>
                    <div class="breakdown-value">{{ count }}</div>
                    <div class="breakdown-bar">
                        <div class="bar-fill {{ severity }}" 
                             style="width: {{ (count / report.metrics.total_findings * 100)|round(1) }}%">
                        </div>
                    </div>
                    <div class="breakdown-percentage">
                        {{ (count / report.metrics.total_findings * 100)|round(1) }}%
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </section>
    
    <!-- Detailed Findings -->
    <section id="detailed-findings" class="detailed-findings">
        <h2><i class="fas fa-file-alt"></i> Detailed Findings</h2>
        
        <div class="findings-controls">
            <div class="filter-controls">
                <label for="severityFilter">Filter by Severity:</label>
                <select id="severityFilter" class="form-control">
                    <option value="all">All Severities</option>
                    <option value="critical">Critical</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                </select>
            </div>
            <div class="search-controls">
                <input type="text" id="findingSearch" class="form-control" placeholder="Search findings...">
                <button id="clearSearch" class="btn btn-secondary">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        
        <div class="findings-container">
            {% for finding in report.findings %}
            <div class="finding-detail-card {{ finding.severity|lower }}" 
                 data-severity="{{ finding.severity|lower }}"
                 data-search="{{ finding.title|lower }} {{ finding.description|lower }}">
                <div class="finding-detail-header">
                    <div class="finding-title-section">
                        <h3>{{ finding.title }}</h3>
                        <div class="finding-meta">
                            <span class="finding-id">ID: {{ finding.id }}</span>
                            <span class="finding-rule">Rule: {{ finding.rule_name }}</span>
                            <span class="finding-category">Category: {{ finding.category }}</span>
                        </div>
                    </div>
                    <div class="finding-severity-section">
                        <span class="severity-badge large {{ finding.severity|lower }}">
                            {{ finding.severity }}
                        </span>
                    </div>
                </div>
                
                <div class="finding-detail-content">
                    <div class="finding-description">
                        <h4>Description</h4>
                        <p>{{ finding.description }}</p>
                    </div>
                    
                    {% if finding.context %}
                    <div class="finding-context">
                        <h4>Context</h4>
                        <pre><code>{{ finding.context|json }}</code></pre>
                    </div>
                    {% endif %}
                    
                    {% if finding.ai_explanation and include_ai_explanations %}
                    <div class="finding-ai-explanation">
                        <h4><i class="fas fa-robot"></i> AI Explanation</h4>
                        <div class="ai-explanation-content">
                            {{ finding.ai_explanation }}
                        </div>
                    </div>
                    {% endif %}
                    
                    {% if finding.recommendations %}
                    <div class="finding-recommendations">
                        <h4><i class="fas fa-lightbulb"></i> Recommendations</h4>
                        <ul>
                            {% for recommendation in finding.recommendations %}
                            <li>{{ recommendation }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    
                    <div class="finding-footer">
                        <div class="finding-status">
                            <span class="status-badge {{ finding.status|lower }}">
                                {{ finding.status }}
                            </span>
                        </div>
                        {% if finding.created_at %}
                        <div class="finding-timestamp">
                            <i class="far fa-clock"></i>
                            {{ finding.created_at }}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% else %}
            <div class="no-findings">
                <i class="fas fa-check-circle"></i>
                <h3>No Findings Detected</h3>
                <p>The audit completed successfully with no issues found.</p>
            </div>
            {% endfor %}
        </div>
        
        <div class="findings-summary-footer">
            <p>Total Findings: {{ report.findings|length }}</p>
        </div>
    </section>
    
    {% if report.recommendations %}
    <!-- Recommendations -->
    <section id="recommendations" class="recommendations">
        <h2><i class="fas fa-tasks"></i> Recommendations</h2>
        
        <div class="recommendations-grid">
            {% for recommendation in report.recommendations %}
            <div class="recommendation-card {{ recommendation.priority|lower }}">
                <div class="recommendation-header">
                    <h3>{{ recommendation.title }}</h3>
                    <span class="priority-badge {{ recommendation.priority|lower }}">
                        {{ recommendation.priority }}
                    </span>
                </div>
                
                <div class="recommendation-content">
                    {% if recommendation.description %}
                    <p class="recommendation-description">{{ recommendation.description }}</p>
                    {% endif %}
                    
                    {% if recommendation.actions %}
                    <div class="recommendation-actions">
                        <h4>Actions</h4>
                        <ul>
                            {% for action in recommendation.actions %}
                            <li>{{ action }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    
                    <div class="recommendation-meta">
                        <div class="meta-item">
                            <i class="far fa-clock"></i>
                            <span>Timeline: {{ recommendation.timeline }}</span>
                        </div>
                        {% if recommendation.owner %}
                        <div class="meta-item">
                            <i class="fas fa-user"></i>
                            <span>Owner: {{ recommendation.owner }}</span>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    {% endif %}
    
    {% if report.appendix %}
    <!-- Appendix -->
    <section id="appendix" class="appendix">
        <h2><i class="fas fa-paperclip"></i> Appendix</h2>
        
        {% for section, content in report.appendix.items() %}
        <div class="appendix-section">
            <h3>{{ section }}</h3>
            
            {% if content is string %}
            <div class="appendix-text">{{ content }}</div>
            {% elif content is iterable %}
            <ul class="appendix-list">
                {% for item in content %}
                <li>{{ item }}</li>
                {% endfor %}
            </ul>
            {% else %}
            <pre class="appendix-code"><code>{{ content|json }}</code></pre>
            {% endif %}
        </div>
        {% endfor %}
    </section>
    {% endif %}
</div>

<!-- Back to Top Button -->
<button id="backToTop" class="back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block extra_scripts %}
<script>
    // Initialize charts
    document.addEventListener('DOMContentLoaded', function() {
        // Severity Chart
        const severityCtx = document.getElementById('severityChart').getContext('2d');
        const severityChart = new Chart(severityCtx, {
            type: 'doughnut',
            data: {
                labels: ['Critical', 'High', 'Medium', 'Low'],
                datasets: [{
                    data: [
                        {{ report.metrics.critical }},
                        {{ report.metrics.high }},
                        {{ report.metrics.medium }},
                        {{ report.metrics.low }}
                    ],
                    backgroundColor: [
                        '#E74C3C', // Critical
                        '#E67E22', // High
                        '#F1C40F', // Medium
                        '#2ECC71'  // Low
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'bottom'
                    }
                }
            }
        });
        
        // Timeline Chart (example data)
        const timelineCtx = document.getElementById('timelineChart').getContext('2d');
        const timelineChart = new Chart(timelineCtx, {
            type: 'line',
            data: {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                datasets: [{
                    label: 'Findings',
                    data: [12, 19, 15, 25, 22, 30],
                    borderColor: '#3498DB',
                    backgroundColor: 'rgba(52, 152, 219, 0.1)',
                    fill: true,
                    tension: 0.4
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        display: false
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        title: {
                            display: true,
                            text: 'Number of Findings'
                        }
                    },
                    x: {
                        title: {
                            display: true,
                            text: 'Month'
                        }
                    }
                }
            }
        });
        
        // Filter findings by severity
        const severityFilter = document.getElementById('severityFilter');
        severityFilter.addEventListener('change', function() {
            const selectedSeverity = this.value;
            const findingCards = document.querySelectorAll('.finding-detail-card');
            
            findingCards.forEach(card => {
                if (selectedSeverity === 'all' || card.dataset.severity === selectedSeverity) {
                    card.style.display = 'block';
                } else {
                    card.style.display = 'none';
                }
            });
        });
        
        // Search findings
        const searchInput = document.getElementById('findingSearch');
        const clearSearchBtn = document.getElementById('clearSearch');
        
        searchInput.addEventListener('input', function() {
            const searchTerm = this.value.toLowerCase();
            const findingCards = document.querySelectorAll('.finding-detail-card');
            
            findingCards.forEach(card => {
                const searchableText = card.dataset.search;
                if (searchableText.includes(searchTerm)) {
                    card.style.display = 'block';
                } else {
                    card.style.display = 'none';
                }
            });
        });
        
        clearSearchBtn.addEventListener('click', function() {
            searchInput.value = '';
            searchInput.dispatchEvent(new Event('input'));
        });
        
        // Back to top button
        const backToTopBtn = document.getElementById('backToTop');
        
        window.addEventListener('scroll', function() {
            if (window.pageYOffset > 300) {
                backToTopBtn.style.display = 'block';
            } else {
                backToTopBtn.style.display = 'none';
            }
        });
        
        backToTopBtn.addEventListener('click', function() {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
        
        // Expand/collapse finding details
        document.querySelectorAll('.finding-detail-header').forEach(header => {
            header.addEventListener('click', function() {
                const content = this.nextElementSibling;
                content.classList.toggle('expanded');
            });
        });
    });
</script>
{% endblock %}
"""
        
        template_path = Path(config.templates_dir) / "audit_report.html"
        with open(template_path, 'w') as f:
            f.write(template_content)
    
    def _create_default_css(self):
        """Create default CSS styles."""
        css_content = """/* Aquila Audit Report Styles */

:root {
    --primary-color: #2C3E50;
    --secondary-color: #3498DB;
    --accent-color: #E74C3C;
    --success-color: #27AE60;
    --warning-color: #F39C12;
    --light-gray: #ECF0F1;
    --dark-gray: #7F8C8D;
    --critical-color: #E74C3C;
    --high-color: #E67E22;
    --medium-color: #F1C40F;
    --low-color: #2ECC71;
    --border-radius: 8px;
    --box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    --transition: all 0.3s ease;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Inter', sans-serif;
    line-height: 1.6;
    color: #333;
    background-color: #f8f9fa;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}

/* Header Styles */
.report-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 30px;
    background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    color: white;
    border-radius: var(--border-radius);
    margin-bottom: 30px;
    box-shadow: var(--box-shadow);
}

.company-info h1 {
    font-size: 2.5rem;
    margin-bottom: 10px;
    font-weight: 700;
}

.company-info p {
    margin-bottom: 5px;
    opacity: 0.9;
}

.company-info a {
    color: white;
    text-decoration: none;
}

.company-info a:hover {
    text-decoration: underline;
}

.company-logo img {
    max-height: 80px;
    width: auto;
}

/* Cover Page */
.cover-page {
    min-height: 80vh;
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    padding: 40px;
    background: white;
    border-radius: var(--border-radius);
    margin-bottom: 30px;
    box-shadow: var(--box-shadow);
}

.report-title {
    font-size: 3rem;
    color: var(--primary-color);
    margin-bottom: 20px;
}

.report-subtitle {
    font-size: 1.5rem;
    color: var(--secondary-color);
    margin-bottom: 40px;
    font-weight: 400;
}

.report-metadata {
    margin: 40px auto;
    max-width: 600px;
}

.metadata-table {
    width: 100%;
    border-collapse: collapse;
}

.metadata-table th,
.metadata-table td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid var(--light-gray);
}

.metadata-table th {
    font-weight: 600;
    color: var(--primary-color);
    width: 30%;
}

.metadata-table tr:last-child th,
.metadata-table tr:last-child td {
    border-bottom: none;
}

.confidential-banner {
    background-color: var(--critical-color);
    color: white;
    padding: 15px 30px;
    border-radius: var(--border-radius);
    display: inline-flex;
    align-items: center;
    gap: 10px;
    margin-top: 40px;
    font-weight: 600;
}

/* Table of Contents */
.toc-section {
    background: white;
    padding: 30px;
    border-radius: var(--border-radius);
    margin-bottom: 30px;
    box-shadow: var(--box-shadow);
}

.toc-section h2 {
    color: var(--primary-color);
    margin-bottom: 20px;
    display: flex;
    align-items: center;
    gap: 10px;
}

.toc-nav ul {
    list-style: none;
    padding-left: 20px;
}

.toc-nav li {
    margin-bottom: 10px;
}

.toc-nav a {
    color: var(--secondary-color);
    text-decoration: none;
    font-size: 1.1rem;
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 8px 0;
    border-bottom: 1px solid transparent;
    transition: var(--transition);
}

.toc-nav a:hover {
    color: var(--primary-color);
    border-bottom-color: var(--secondary-color);
}

.toc-nav a:before {
    content: '›';
    font-size: 1.2rem;
}

/* Section Styles */
section {
    background: white;
    padding: 40px;
    border-radius: var(--border-radius);
    margin-bottom: 30px;
    box-shadow: var(--box-shadow);
}

section h2 {
    color: var(--primary-color);
    margin-bottom: 30px;
    padding-bottom: 15px;
    border-bottom: 2px solid var(--light-gray);
    display: flex;
    align-items: center;
    gap: 10px;
}

/* Executive Summary */
.summary-text {
    font-size: 1.1rem;
    line-height: 1.8;
    color: #555;
    margin-bottom: 40px;
    padding: 20px;
    background: var(--light-gray);
    border-radius: var(--border-radius);
    border-left: 4px solid var(--secondary-color);
}

.key-metrics {
    margin-bottom: 40px;
}

.metrics-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
    margin-top: 20px;
}

.metric-card {
    padding: 25px;
    border-radius: var(--border-radius);
    text-align: center;
    color: white;
    transition: var(--transition);
    cursor: pointer;
}

.metric-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.2);
}

.metric-card.total {
    background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
}

.metric-card.critical {
    background: linear-gradient(135deg, #E74C3C, #C0392B);
}

.metric-card.high {
    background: linear-gradient(135deg, #E67E22, #D35400);
}

.metric-card.medium {
    background: linear-gradient(135deg, #F1C40F, #F39C12);
}

.metric-card.low {
    background: linear-gradient(135deg, #2ECC71, #27AE60);
}

.metric-card.risk-score {
    background: linear-gradient(135deg, #9B59B6, #8E44AD);
}

.metric-label {
    font-size: 0.9rem;
    opacity: 0.9;
    margin-bottom: 10px;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.metric-value {
    font-size: 2.5rem;
    font-weight: 700;
}

/* Findings Styles */
.findings-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding: 20px;
    background: var(--light-gray);
    border-radius: var(--border-radius);
}

.filter-controls,
.search-controls {
    display: flex;
    align-items: center;
    gap: 10px;
}

.form-control {
    padding: 10px 15px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 1rem;
    transition: var(--transition);
}

.form-control:focus {
    outline: none;
    border-color: var(--secondary-color);
    box-shadow: 0 0 0 3px rgba(52, 152, 219, 0.2);
}

.btn {
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
    transition: var(--transition);
}

.btn-secondary {
    background: var(--dark-gray);
    color: white;
}

.btn-secondary:hover {
    background: #6c757d;
}

/* Finding Cards */
.finding-card,
.finding-detail-card {
    background: white;
    border-radius: var(--border-radius);
    margin-bottom: 20px;
    overflow: hidden;
    transition: var(--transition);
    border: 1px solid var(--light-gray);
}

.finding-detail-card {
    border-left: 4px solid;
}

.finding-detail-card.critical {
    border-left-color: var(--critical-color);
}

.finding-detail-card.high {
    border-left-color: var(--high-color);
}

.finding-detail-card.medium {
    border-left-color: var(--medium-color);
}

.finding-detail-card.low {
    border-left-color: var(--low-color);
}

.finding-detail-card:hover {
    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1);
}

.finding-detail-header {
    padding: 20px;
    background: var(--light-gray);
    display: flex;
    justify-content: space-between;
    align-items: center;
    cursor: pointer;
}

.finding-title-section h3 {
    color: var(--primary-color);
    margin-bottom: 5px;
}

.finding-meta {
    display: flex;
    gap: 15px;
    font-size: 0.9rem;
    color: var(--dark-gray);
}

.finding-meta span {
    display: flex;
    align-items: center;
    gap: 5px;
}

.severity-badge {
    padding: 6px 12px;
    border-radius: 20px;
    font-size: 0.8rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.severity-badge.large {
    padding: 10px 20px;
    font-size: 1rem;
}

.severity-badge.critical {
    background-color: var(--critical-color);
    color: white;
}

.severity-badge.high {
    background-color: var(--high-color);
    color: white;
}

.severity-badge.medium {
    background-color: var(--medium-color);
    color: black;
}

.severity-badge.low {
    background-color: var(--low-color);
    color: white;
}

.finding-detail-content {
    padding: 20px;
    display: none;
}

.finding-detail-content.expanded {
    display: block;
}

.finding-detail-content h4 {
    color: var(--primary-color);
    margin: 15px 0 10px 0;
    font-size: 1.1rem;
}

.finding-context pre {
    background: #f8f9fa;
    padding: 15px;
    border-radius: 4px;
    overflow-x: auto;
    border: 1px solid #dee2e6;
}

.finding-context code {
    font-family: 'Courier New', monospace;
    font-size: 0.9rem;
}

.ai-explanation-content {
    background: #f0f7ff;
    padding: 15px;
    border-radius: 4px;
    border-left: 4px solid var(--secondary-color);
}

.finding-recommendations ul {
    list-style: none;
    padding-left: 0;
}

.finding-recommendations li {
    padding: 8px 0;
    padding-left: 25px;
    position: relative;
}

.finding-recommendations li:before {
    content: '✓';
    position: absolute;
    left: 0;
    color: var(--success-color);
    font-weight: bold;
}

.finding-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 20px;
    padding-top: 20px;
    border-top: 1px solid var(--light-gray);
}

.status-badge {
    padding: 6px 12px;
    border-radius: 4px;
    font-size: 0.8rem;
    font-weight: 600;
}

.status-badge.open {
    background-color: #fff3cd;
    color: #856404;
}

.status-badge.in-progress {
    background-color: #cce5ff;
    color: #004085;
}

.status-badge.closed {
    background-color: #d4edda;
    color: #155724;
}

.finding-timestamp {
    color: var(--dark-gray);
    font-size: 0.9rem;
}

/* Charts */
.charts-container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
    gap: 30px;
    margin-bottom: 40px;
}

.chart-card {
    background: white;
    padding: 25px;
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow);
}

.chart-card h3 {
    color: var(--primary-color);
    margin-bottom: 20px;
    font-size: 1.2rem;
}

/* Severity Breakdown */
.severity-breakdown {
    background: white;
    padding: 25px;
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow);
}

.breakdown-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
    margin-top: 20px;
}

.breakdown-item {
    padding: 20px;
    border-radius: var(--border-radius);
    background: var(--light-gray);
}

.breakdown-item.critical {
    border-left: 4px solid var(--critical-color);
}

.breakdown-item.high {
    border-left: 4px solid var(--high-color);
}

.breakdown-item.medium {
    border-left: 4px solid var(--medium-color);
}

.breakdown-item.low {
    border-left: 4px solid var(--low-color);
}

.breakdown-label {
    font-weight: 600;
    color: var(--primary-color);
    text-transform: uppercase;
    font-size: 0.9rem;
    margin-bottom: 10px;
}

.breakdown-value {
    font-size: 2rem;
    font-weight: 700;
    margin-bottom: 10px;
}

.breakdown-bar {
    height: 10px;
    background: #dee2e6;
    border-radius: 5px;
    margin-bottom: 10px;
    overflow: hidden;
}

.bar-fill {
    height: 100%;
    border-radius: 5px;
}

.bar-fill.critical {
    background-color: var(--critical-color);
}

.bar-fill.high {
    background-color: var(--high-color);
}

.bar-fill.medium {
    background-color: var(--medium-color);
}

.bar-fill.low {
    background-color: var(--low-color);
}

.breakdown-percentage {
    text-align: right;
    font-weight: 600;
    color: var(--dark-gray);
}

/* Recommendations */
.recommendations-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 25px;
    margin-top: 20px;
}

.recommendation-card {
    background: white;
    border-radius: var(--border-radius);
    padding: 25px;
    box-shadow: var(--box-shadow);
    border-top: 4px solid;
    transition: var(--transition);
}

.recommendation-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);
}

.recommendation-card.high {
    border-top-color: var(--critical-color);
}

.recommendation-card.medium {
    border-top-color: var(--medium-color);
}

.recommendation-card.low {
    border-top-color: var(--low-color);
}

.recommendation-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 15px;
}

.recommendation-header h3 {
    color: var(--primary-color);
    font-size: 1.2rem;
    flex: 1;
    margin-right: 15px;
}

.priority-badge {
    padding: 6px 12px;
    border-radius: 20px;
    font-size: 0.8rem;
    font-weight: 600;
    text-transform: uppercase;
}

.priority-badge.high {
    background-color: var(--critical-color);
    color: white;
}

.priority-badge.medium {
    background-color: var(--medium-color);
    color: black;
}

.priority-badge.low {
    background-color: var(--low-color);
    color: white;
}

.recommendation-description {
    color: #555;
    margin-bottom: 15px;
    line-height: 1.6;
}

.recommendation-actions ul {
    list-style: none;
    padding-left: 0;
}

.recommendation-actions li {
    padding: 5px 0;
    padding-left: 25px;
    position: relative;
}

.recommendation-actions li:before {
    content: '→';
    position: absolute;
    left: 0;
    color: var(--secondary-color);
}

.recommendation-meta {
    display: flex;
    gap: 20px;
    margin-top: 20px;
    padding-top: 20px;
    border-top: 1px solid var(--light-gray);
}

.meta-item {
    display: flex;
    align-items: center;
    gap: 8px;
    color: var(--dark-gray);
    font-size: 0.9rem;
}

/* Appendix */
.appendix-section {
    margin-bottom: 30px;
    padding: 20px;
    background: var(--light-gray);
    border-radius: var(--border-radius);
}

.appendix-section h3 {
    color: var(--primary-color);
    margin-bottom: 15px;
    font-size: 1.1rem;
}

.appendix-text {
    line-height: 1.6;
    color: #555;
}

.appendix-list {
    list-style: none;
    padding-left: 0;
}

.appendix-list li {
    padding: 8px 0;
    padding-left: 25px;
    position: relative;
}

.appendix-list li:before {
    content: '•';
    position: absolute;
    left: 10px;
    color: var(--secondary-color);
    font-size: 1.2rem;
}

.appendix-code {
    background: #f8f9fa;
    padding: 15px;
    border-radius: 4px;
    overflow-x: auto;
    font-family: 'Courier New', monospace;
    font-size: 0.9rem;
}

/* Footer */
.report-footer {
    margin-top: 50px;
    padding: 30px;
    background: var(--primary-color);
    color: white;
    border-radius: var(--border-radius);
    text-align: center;
}

.footer-content p {
    margin-bottom: 10px;
}

.confidential-notice {
    color: #ff6b6b;
    font-weight: 600;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    margin: 15px 0;
}

.footer-disclaimer {
    font-size: 0.9rem;
    opacity: 0.8;
    margin-top: 20px;
}

/* Back to Top Button */
.back-to-top {
    position: fixed;
    bottom: 30px;
    right: 30px;
    width: 50px;
    height: 50px;
    background: var(--secondary-color);
    color: white;
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    align-items: center;
    justify-content: center;
    font-size: 1.2rem;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
    transition: var(--transition);
    z-index: 1000;
}

.back-to-top:hover {
    background: var(--primary-color);
    transform: translateY(-3px);
}

/* Responsive Design */
@media (max-width: 768px) {
    .container {
        padding: 10px;
    }
    
    .report-header {
        flex-direction: column;
        text-align: center;
        gap: 20px;
    }
    
    .metrics-grid,
    .charts-container,
    .recommendations-grid {
        grid-template-columns: 1fr;
    }
    
    .findings-controls {
        flex-direction: column;
        gap: 15px;
        align-items: stretch;
    }
    
    .filter-controls,
    .search-controls {
        flex-direction: column;
        align-items: stretch;
    }
    
    .finding-detail-header {
        flex-direction: column;
        align-items: flex-start;
        gap: 15px;
    }
    
    .finding-meta {
        flex-direction: column;
        gap: 5px;
    }
    
    .finding-footer {
        flex-direction: column;
        gap: 10px;
        align-items: flex-start;
    }
    
    .cover-page {
        padding: 20px;
    }
    
    .report-title {
        font-size: 2rem;
    }
    
    .report-subtitle {
        font-size: 1.2rem;
    }
}

/* Print Styles */
@media print {
    .report-header,
    .toc-section,
    .findings-controls,
    .back-to-top {
        display: none;
    }
    
    section {
        break-inside: avoid;
        box-shadow: none;
        border: 1px solid #ddd;
    }
    
    .metric-card,
    .finding-detail-card,
    .recommendation-card {
        break-inside: avoid;
    }
    
    .finding-detail-content {
        display: block !important;
    }
    
    body {
        font-size: 12pt;
        line-height: 1.4;
    }
}
"""
        
        css_path = Path(config.templates_dir) / "style.css"
        with open(css_path, 'w') as f:
            f.write(css_content)
    
    def _get_severity_color(self, severity: str) -> str:
        """Get CSS color for severity level."""
        colors = {
            'CRITICAL': '#E74C3C',
            'HIGH': '#E67E22',
            'MEDIUM': '#F1C40F',
            'LOW': '#2ECC71'
        }
        return colors.get(severity.upper(), '#7F8C8D')
    
    def _get_priority_color(self, priority: str) -> str:
        """Get CSS color for priority level."""
        colors = {
            'HIGH': '#E74C3C',
            'MEDIUM': '#F1C40F',
            'LOW': '#2ECC71'
        }
        return colors.get(priority.upper(), '#7F8C8D')
    
    def generate_report(
        self,
        report_data: Dict[str, Any],
        output_path: str,
        include_interactive: bool = True
    ) -> Dict[str, Any]:
        """
        Generate HTML report.
        
        Args:
            report_data: Report data
            output_path: Output file path
            include_interactive: Whether to include interactive features
        
        Returns:
            Generation metadata
        """
        start_time = datetime.now()
        
        try:
            # Prepare template context
            context = {
                'report': report_data,
                'company_name': config.company_name,
                'company_address': config.company_address,
                'company_website': config.company_website,
                'company_logo_path': config.company_logo_path,
                'company_logo_exists': os.path.exists(config.company_logo_path),
                'generated_date': report_data.get('generated_date', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
                'generated_by': report_data.get('generated_by', 'Aquila Audit System'),
                'confidential': report_data.get('confidential', True),
                'include_ai_explanations': config.include_ai_explanations,
                'include_interactive': include_interactive
            }
            
            # Load and render template
            template = self.env.get_template("audit_report.html")
            html_content = template.render(**context)
            
            # Write to file
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            # Calculate metadata
            end_time = datetime.now()
            duration = (end_time - start_time).total_seconds()
            
            # Get file size
            file_size = os.path.getsize(output_path)
            
            metadata = {
                'success': True,
                'output_path': output_path,
                'file_size': file_size,
                'generation_time': duration,
                'format': 'html',
                'timestamp': datetime.now().isoformat(),
                'interactive': include_interactive
            }
            
            logger.info(f"HTML report generated: {output_path} ({file_size} bytes)")
            
            return metadata
            
        except Exception as e:
            logger.error(f"Error generating HTML report: {str(e)}")
            raise


# Global HTML generator instance
html_generator = HTMLGenerator()