"""fix tenant foreign keys

Revision ID: 064c4f6c7b99
Revises: 1b9232220c2b
Create Date: 2025-12-28 13:02:04.798312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '064c4f6c7b99'
down_revision = '1b9232220c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('billing_plans', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'billing_plans', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('file_chunks', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'file_chunks', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('file_validations', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'file_validations', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('files', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'files', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('finding_comments', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'finding_comments', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('findings', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'findings', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('rule_sets', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'rule_sets', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('rule_templates', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'rule_templates', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('rules', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'rules', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('ruleset_rules', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'ruleset_rules', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('user_roles', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.create_foreign_key(None, 'user_roles', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.alter_column('user_roles', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'ruleset_rules', type_='foreignkey')
    op.alter_column('ruleset_rules', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.alter_column('rules', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'rule_templates', type_='foreignkey')
    op.alter_column('rule_templates', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'rule_sets', type_='foreignkey')
    op.alter_column('rule_sets', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.alter_column('findings', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'finding_comments', type_='foreignkey')
    op.alter_column('finding_comments', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.alter_column('files', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'file_validations', type_='foreignkey')
    op.alter_column('file_validations', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'file_chunks', type_='foreignkey')
    op.alter_column('file_chunks', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'billing_plans', type_='foreignkey')
    op.alter_column('billing_plans', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant identifier for data isolation',
               existing_nullable=False)
    # ### end Alembic commands ###