"""create_tables

Revision ID: 3f9b361e6896
Revises: 4bd2ef5d257c
Create Date: 2025-12-26 12:00:27.490955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f9b361e6896'
down_revision = '4bd2ef5d257c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###