"""convert user_tenants to declarative model

Revision ID: bdeec47b9879
Revises: e000cef8934a
Create Date: 2025-12-28 13:56:14.562156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdeec47b9879'
down_revision = 'e000cef8934a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###